[package]
name = "ebpf-vc"
authors = [ "Troels Korreman" ]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bpaf = { version = "0.7.7", features = ["derive"] }
itertools = "0.10.5"
nom = "7.1.2"
